### ISSUE TITLE
🎨 Add hover effects to toolbar buttons

### ISSUE THREAD

**Issue by baris-sinapli** [baris-sinapli/mermaid-diagram#2]
## 📝 Task
Add simple hover effects to toolbar buttons for better user experience.

## ✅ What to do
- Add CSS hover states to toolbar buttons
- Use existing CSS variables for colors
- Keep effects subtle and professional

## 📍 Files to modify
- `src/lib/components/editor/Toolbar.svelte`

## 💡 Example
```css
.btn:hover {
  background: var(--accent);
  transform: translateY(-1px);
}
```

## 🎯 Acceptance criteria
- [ ] Hover effects on all toolbar buttons
- [ ] Uses existing CSS variables
- [ ] Smooth transition animations
- [ ] No accessibility issues

**Estimated time: 30-45 minutes**
